import fs from "fs";
const J = { "2. Your Player Character": {} };
const P = J["2. Your Player Character"];

P["Name"] = `<p>종족과 직업을 골랐다면 이제 모험가의 이름을 지을 차례입니다. 종족마다 그 종족에서 흔한 이름 여섯 개가 실려 있습니다. 그중에서 고르거나 굴리고, 원한다면 직접 지어도 좋습니다. </p><p><strong>별명</strong>: 모험가들 사이에서는 별명을 갖는 것이 흔한 관습이며, 대개 겉모습이나 성격, 살아온 내력을 드러내는 이름을 씁니다. 게임을 시작할 때 별명을 고르거나, 원한다면 나중에 붙여도 됩니다. 직업별로 흔한 별명이 여럿 실려 있습니다. </p>`;

P["Attributes"] = `<p>당신의 모험가에게는 기본적인 신체·정신 역량을 나타내는 기본 능력치 여섯 개가 있으며, 값은 3에서 18까지입니다. 높을수록 좋습니다. </p><p>시작 수치: 4D6을 굴려 가장 나쁜 주사위 하나를 빼면 3에서 18 사이의 값이 나옵니다. 그 값을 원하는 능력치에 배정하세요. 이 과정을 다섯 번 더 되풀이해 능력치마다 값을 배정합니다. 굴릴 때마다 곧바로 배정해야 하지만, 다 끝난 뒤에 두 값을 서로 맞바꿀 수는 있습니다. </p><p>그런 다음 나이에 따라 능력치를 조정합니다. 나이와 상관없이 능력치는 결코 18을 넘을 수 없다는 점에 유의하세요. 한 번 배정한 능력치는 게임 도중에 좀처럼 바뀌지 않습니다. </p><p></p><blockquote class="info foundry"><h3>Foundry VTT</h3><p>Foundry VTT에서 4D6을 굴려 가장 나쁜 주사위를 빼려면 채팅에 다음과 같이 입력하세요.<br />"/roll 4D6k3h" ([[/roll 4D6k3h]])</p></blockquote><p></p><p><strong>힘(STR):</strong> 순수한 근력. </p><p><strong>건강(CON):</strong> 신체적 건강함과 끈기. </p><p><strong>민첩(AGL):</strong> 몸놀림, 속도, 섬세한 손놀림. </p><p><strong>지능(INT):</strong> 명민함, 지성, 추론 능력. </p><p><strong>의지(WIL):</strong> 자기 절제와 집중력. </p><p><strong>매력(CHA):</strong> 인격의 힘과 공감 능력. </p><p></p><blockquote class="info"><h3>다른 방법</h3><p>플레이어 캐릭터의 능력치를 정하는 방법은 그 밖에도 많습니다. 여섯 개를 모두 굴린 뒤 결과를 나중에 배분하거나, 굴림을 모두 더해 큰 점수 더미를 만든 뒤 자유롭게 나누는 식으로 말입니다. 모임 전체가 동의한다면 원하는 어떤 방법을 써도 좋습니다.</p></blockquote>`;

P["Derived Ratings"] = `<p>능력치를 바탕으로 여러 곳에 쓰이는 파생 수치가 몇 가지 나옵니다.</p><h2>이동력</h2><p>이 수치는 전투 한 라운드에 몇 미터를 달릴 수 있는지 결정합니다(@UUID[JournalEntry.SbbSMsuvWeo3HaID.JournalEntryPage.KrSXg7HKmfo7xRcI#movement]{이동} 참조). 종족에 따라 정해지고 민첩으로 수정됩니다.</p><p></p><div class="display-table"><table style="width:50%"><tbody><tr><th style="width:50%">종족</th><th style="width:50%;text-align:center">이동력</th></tr><tr><td>인간</td><td style="text-align:center">10</td></tr><tr><td>하플링</td><td style="text-align:center">8</td></tr><tr><td>드워프</td><td style="text-align:center">8</td></tr><tr><td>엘프</td><td style="text-align:center">10</td></tr><tr><td>말라드</td><td style="text-align:center">8</td></tr><tr><td>울프킨</td><td style="text-align:center">12</td></tr><tr><td>민첩 1-6</td><td style="text-align:center">-4</td></tr><tr><td>민첩 7-9</td><td style="text-align:center">-2</td></tr><tr><td>민첩 13-15</td><td style="text-align:center">+2</td></tr><tr><td>민첩 16-18</td><td style="text-align:center">+4</td></tr></tbody></table></div><p></p><h2>피해 보너스</h2><p>피해 보너스는 당신의 공격이 입히는 피해를 늘립니다. 피해 보너스는 힘 기반 무기용과 민첩 기반 무기용 두 가지가 따로 있습니다.</p><p></p><div class="display-table"><table style="width:50%"><tbody><tr><th style="width:50%">힘/민첩</th><th style="width:50%;text-align:center">피해 보너스</th></tr><tr><td>&lt;= 12</td><td style="text-align:center">-</td></tr><tr><td>13-16</td><td style="text-align:center">+D4</td></tr><tr><td>17+</td><td style="text-align:center">+D6</td></tr></tbody></table></div><h2>생명력(HP)</h2><p>이 수치는 얼마나 많은 피해를 견딜 수 있는지 결정합니다. 최대 HP는 건강과 같지만 영웅 능력 강건함으로 늘릴 수 있습니다. 피해에 관한 자세한 내용은 @UUID[JournalEntry.SbbSMsuvWeo3HaID]{4. 전투와 피해}를 참고하세요.</p><h2>의지력(WP)</h2><p>의지력은 마법은 물론 타고난 능력과 영웅 능력에도 쓰입니다. 최대 WP는 의지와 같지만 영웅 능력 집중으로 늘릴 수 있습니다.</p>`;

P["Skills"] = `<p>기술은 모험가로 살아오는 동안(또는 그전에) 익힌 지식과 능력을 나타냅니다. 게임에서 특정 행동을 얼마나 잘 해내는지를 결정하므로 중요합니다. 기본 게임에는 기본 기술 서른 개가 있으며 모두 다음 장에서 자세히 설명합니다. 기술은 1에서 18까지의 기술 수치로 잽니다. 높을수록 좋습니다.</p><p><strong>기본 확률</strong>: 모든 기술은 능력치 하나와 이어져 있고, 그 능력치가 그 기술의 기본 확률을 결정합니다. 이는 캐릭터 시트와 @UUID[JournalEntry.V4R4dCuKSK2mi8RF]{3. 기술}에 표시되어 있습니다. 기본 확률은 자동으로 얻는 "공짜" 기술 수치입니다. 아래 표를 참고하세요.</p><div class="display-table"><table style="width:50%"><tbody><tr><th style="width:50%">능력치</th><th style="width:50%;text-align:center">기본 확률</th></tr><tr><td>1-5</td><td style="text-align:center">3</td></tr><tr><td>6-8</td><td style="text-align:center">4</td></tr><tr><td>9-12</td><td style="text-align:center">5</td></tr><tr><td>13-15</td><td style="text-align:center">6</td></tr><tr><td>16-18</td><td style="text-align:center">7</td></tr></tbody></table></div><p><strong>시작 기술 수치</strong>: 기본 확률에 더해, 나이에 따라 여덟·열·열두 개의 훈련된 기술을 지니고 시작합니다. 게임을 시작할 때 훈련된 기술의 수치는 기본 확률의 두 배입니다. 훈련된 기술 여섯 개는 자기 직업 목록에서 골라야 합니다. 나머지(나이에 따라 둘·넷·여섯)는 자유롭게 고릅니다. 게임 도중에 기술 수치를 올릴 수 있습니다.</p><blockquote class="info"><h3>Foundry VTT</h3><p>캐릭터 시트의 기술 탭에서 기술 수치를 편집해 훈련된 기술을 고르세요. 새 값은 기본 확률의 두 배여야 합니다.</p></blockquote><p><strong>보조 기술</strong>: 기본 기술 말고도 마법 학파 같은 보조 기술이 있습니다. 이 기본 게임에서는 어떤 보조 기술에도 기본 확률이 주어지지 않지만, 앞으로 나올 확장판과 보충 자료에서 달라질 수 있습니다.</p><blockquote class="info"><h3>마법</h3><p>마법은 여러 학파로 나뉘며 학파마다 별개의 기술입니다. 갓 만든 마법사는 마법 학파를 하나 골라야 하고, 그것이 훈련된 기술 가운데 하나가 됩니다(지능 기반). 자기 학파나 일반 마법에서 등급 1 주문 셋과 마법 재주 셋을 고를 수 있습니다.</p><p>게임 도중에 더 많은 주문과 마법 학파를 배울 수 있습니다. 마법에 관한 자세한 내용은 @UUID[JournalEntry.BHzSGEPaCGVadFsb]{5. 마법}을 참고하세요.</p></blockquote>`;

P["Heroic Abilities"] = `<p>영웅 능력은 게임에서 특정한 이점과 혜택을 주는 특별한 능력입니다. 다음 장에서 여러 영웅 능력을 설명하며, 앞으로 나올 보충 자료에서 더 추가될 수 있습니다.</p><p>게임을 시작할 때 직업에 따라 정해지는 영웅 능력 하나를 지닙니다. 플레이 도중에 새 영웅 능력을 얻을 수 있습니다(@UUID[.8oP09yp6neygtjVn]{경험} 참조). 일부 영웅 능력은 최소 기술 수치를 요구한다는 점에 유의하세요. 그런 요구 조건은 시작 영웅 능력에는 적용되지 않습니다.</p><p><strong>마법사</strong>: 마법사를 플레이한다면 게임을 시작할 때 영웅 능력을 얻지 않습니다. 마법이 그 아쉬움을 메워 줄 테니까요! 다만 플레이 도중에는 다른 직업과 똑같이 새 영웅 능력을 얻을 수 있습니다.</p><p></p><blockquote class="optional"><h3>다른 능력</h3><p>직업에 정해진 영웅 능력이 만들고 싶은 캐릭터와 정말 맞지 않는다고 느낀다면, GM은 다른 시작 능력을 고르도록 허락할 수 있습니다.</p></blockquote>`;

fs.writeFileSync("jn_08.json", JSON.stringify(J, null, 1));
let n = 0; for (const p of Object.values(J)) n += Object.keys(p).length;
console.log("jn_08:", Object.keys(J).length, "저널,", n, "페이지");
