import fs from "fs";
const J = { "The Castle of the Robber Knight": {} };
const P = J["The Castle of the Robber Knight"];
const M = n => `modules/dragonbane-coreset/assets/tiles/marker-${n}.webp`;

P["The Castle of the Robber Knight"] = `<blockquote class="info"><p>이틀을 걸어 마침내 목적지에 닿았다. 풀 덮인 언덕이 눈앞에 우뚝 솟아 있고, 그 마루에는 무너진 요새가 앉아 있다. 약탈 기사의 성이다. 마을 여관 난롯불의 온기는 이제 아득하지만, 그 노파의 말은 모두가 기억한다. 오래전 로트가르 울프스베인이라는 사악한 약탈 기사가 이 지역을 괴롭히며 닥치는 대로 노략질했다. 그는 인간이든 드워프든 엘프든 가리지 않고 모두와 싸웠지만, 끝내 그를 무너뜨린 것은 오크였다. 오크 부족 하나가 울프스베인의 성으로 진군해 들이쳤다. 그날 많은 목숨이 스러졌지만 결국 울프스베인은 쓰러졌고 그의 성은 불길에 휩싸였다. 그 뒤 용감한 보물 사냥꾼들이 옛 보물을 찾아 약탈 기사의 성을 뒤지려 들었으나, 돌아온 이는 아무도 없었다. 당신들이 그 첫 번째가 될 것인가?</p></blockquote><img src="modules/dragonbane-coreset/assets/artwork/castle.webp" />`;

P["Introduction"] = `<p>이 어드벤처는 <em>드래곤베인</em>의 간단한 입문편입니다. 더 많은 어드벤처는 @UUID[Compendium.dragonbane-coreset.dragonbane-coreset.cyRMws3pSf1CLsdB]{드래곤베인 - 어드벤처}에서 볼 수 있습니다. 플레이어라면 지금 읽기를 멈추세요. 아래 내용은 GM 전용입니다.</p><p><em>드래곤베인</em>의 어드벤처에는 미리 정해진 줄거리가 없으며, 대개 플레이어 캐릭터들이 흥미로운 장소를 탐험하게 하는 것이 핵심입니다. 다시 말해 약탈 기사의 성에는 정해진 결말이 없습니다.</p><p>먼저 앞 쪽의 그림을 플레이어들에게 보여 주고 그 위의 글을 읽어 주세요.</p><img style="width:50%;transform:rotate(45deg)" src="modules/dragonbane-coreset/assets/artwork/book.webp" />`;

P["The Situation"] = `<p>아주 오래전, 이 어드벤처의 무대가 되는 지역을 잔혹한 약탈 기사가 짓밟았습니다. 그의 이름은 로트가르 울프스베인이었고, 인간이든 드워프든 엘프든 오크든 앞을 가로막는 모두와 싸웠습니다. 그가 부는 무시무시한 전쟁 뿔피리 소리는 적들의 피를 얼어붙게 했습니다.</p><p>울프스베인이 어찌나 미움을 샀던지, 오랜 세월 원수로 지내던 옛 종족들이 반목을 접고 힘을 합쳐 공동의 적에 맞섰습니다. 마침내 오크 무리가 울프스베인이 웅크린 성을 에워쌌습니다. 성을 두고 벌어진 싸움은 피비린내가 진동했고 많은 오크가 약탈 기사의 칼날에 쓰러졌지만, 끝내 그들이 그를 제압했습니다. 로트가르 울프스베인은 성이 불길에 삼켜지는 가운데 오크의 시미터에 목이 잘렸습니다. 약탈 기사의 공포 통치는 그렇게 끝났습니다.</p><p>여러 해가 흐른 지금, 싸움의 소리는 잦아들었지만 약탈 기사의 성 폐허는 여전히 서 있습니다.</p><p>달빛 밝은 밤이면 지나가던 나그네들이 울프스베인의 전쟁 뿔피리 소리를 듣고, 머리 없는 약탈 기사가 유령의 모습으로 나타나는 것을 보았다고 합니다. 폐허 근처에서 상단과 모험가가 사라졌다는 소문이 돌아, 요즘은 대부분 그 언덕을 멀리 돌아갑니다.</p><p>약탈 기사가 자기 성을 다시 걷고 있다는 것은 사실입니다. 그러나 아무도 모르는 것이 있습니다. 교활한 잘도가 이끄는 고블린 산적 무리가 사람들을 폐허에서 쫓아내려고 그 머리 없는 와이트를 불러내고 있다는 사실입니다. 그들은 이 성을 자기네 것으로 삼았고, 그곳을 근거지로 주변 지역을 습격하고 있습니다.</p><h3>무작위 사건</h3><p>플레이어 캐릭터들이 성에서 방을 뒤지거나 짧게 쉬며 온전히 1스트레치를 보낼 때마다 아래 표를 굴릴 수 있습니다.</p><p>@DisplayTable[RollTable.Nap859ovPQqdl5J9]{무작위 사건}</p>`;

P["The Castle"] = `<p>플레이어 캐릭터들이 약탈 기사의 성 안팎에서 탐험할 수 있는 장소들입니다.</p><p></p><div class="flexrow"><div class="flexcol"><div class="flexrow"><img style="max-height:2em;max-width:2em" src="${M(1)}" /><p>@UUID[.PdfGsjBj3GzA0kfC]{옛길}</p></div><div class="flexrow"><img style="max-height:2em;max-width:2em" src="${M(2)}" /><p>@UUID[.AyqBduK7399qDa2x]{문루}</p></div><div class="flexrow"><img style="max-height:2em;max-width:2em" src="${M(3)}" /><p>@UUID[.XWsrpIK3ACbmrhpG]{안뜰}</p></div></div><div class="flexcol"><div class="flexrow"><img style="max-height:2em;max-width:2em" src="${M(4)}" /><p>@UUID[.KX4CV98SdrCz6fMf]{대전당}</p></div><div class="flexrow"><img style="max-height:2em;max-width:2em" src="${M(5)}" /><p>@UUID[.u0UKdabOkp3vUdhk]{지하실}</p></div><div class="flexrow"><img style="max-height:2em;max-width:2em" src="${M(6)}" /><p>@UUID[.oCTJJB8qNN46mDE7]{탑}</p></div></div></div><p></p><img src="modules/dragonbane-coreset/assets/maps/castle-alpha.webp" />`;

P["Old Road"] = `<blockquote class="info"><p><em>덤불과 잡초에 가려 겨우 보이는 낡은 포석 길이 언덕 위로 굽이쳐 오른다. 그 끝에는 어둡고 무너져 가는 성 폐허가 어른거린다. 근처 어딘가에서 큰까마귀가 까악거린다.</em></p></blockquote><ul><li><p><strong>덤불:</strong> 길은 일부가 수풀에 덮여 있고 오래 쓰이지 않았습니다. 고블린들은 길과 나란히 난 좁은 오솔길로 다니기를 좋아합니다. 플레이어 캐릭터들이 주변을 살피면 그 길을 발견합니다.</p></li><li style="color:red"><p style="color:black"><em><strong style="color:red">투구:</strong> 언덕 중턱에 그을린 쇠로 된 낡은 @UUID[Item.c0JttpFm82gW6uSy]{투구}가 덤불에 반쯤 가려져 있습니다. 오래되었는데도 쓰는 데 아무 문제가 없습니다(방어도 +1, 감지 굴림에 불리점). 양옆에 날카로운 가시가 튀어나와 험상궂게 생겼습니다. 캐릭터들에게 신화와 전설을 굴리게 하세요. 성공하면 이 투구를 오크가 벼렸음을 알아챕니다. 이것을 쓴 사람은 어드벤처 뒷부분에서 약탈 기사의 와이트와 마주쳤을 때 곤경에 빠집니다.</em></p></li></ul>`;

P["Gate House"] = `<blockquote class="info"><p><em>길 끝에 한때는 위풍당당했을 낡은 성이 솟아 있다. 지금은 일부가 무너진 성벽이 잿빛 하늘을 배경으로 실루엣을 드리운 초라한 폐허일 뿐이다. 눈앞에는 그을리고 썩은 나무로 된 부서진 성문이 있다. 바람이 안뜰로 스며들며 희미하게 흐느낀다.</em></p></blockquote><ul><li><p><strong>성문:</strong> 그을린 나무로 된 두 짝 문이 안뜰 입구에 열린 채 걸려 있습니다.</p></li><li style="color:red"><p style="color:black"><em><strong style="color:red">올가미:</strong> 플레이어들이 성문을 살펴본다고 하면 숨은 것 찾기를 굴릴 수 있습니다. 성공하면 입구를 가로질러 무릎 높이에 팽팽히 걸린 가느다란 걸림줄이 드러납니다. 이 줄은 성문 안쪽의 방울에 이어져 있습니다. 플레이어 캐릭터들이 이 함정을 알아채지 못하면 성문을 지날 때 발동되며, @UUID[.XWsrpIK3ACbmrhpG]{안뜰}의 나무에서 고블린들이 매복 공격을 합니다.</em></p></li><li><p><strong>구멍:</strong> 입구 바로 안쪽에 어두운 구멍이 있습니다. 땅이 옛 지하실로 무너져 내려, 차갑고 단단한 돌바닥까지 4미터 낙차가 생겼습니다. 플레이어 캐릭터들은 곡예에 성공해야 안뜰 쪽으로 건너갈 수 있습니다. 구멍 반대편에 긴 널빤지가 있어 임시 다리로 쓸 수 있으며, 이를 쓰면 굴림에 이점을 얻습니다. 실패하면 그 플레이어 캐릭터는 @UUID[.u0UKdabOkp3vUdhk]{지하실}로 굴러떨어져 [[/damage 2D6 bludgeoning]]을 받습니다. 각 플레이어 캐릭터는 곡예를 다시 굴려 낙하 충격을 줄일 수 있으며, 성공하면 피해가 [[/damage D6 bludgeoning]]으로 줄어듭니다.</p></li></ul>`;

fs.writeFileSync("jn_17.json", JSON.stringify(J, null, 1));
let n = 0; for (const p of Object.values(J)) n += Object.keys(p).length;
console.log("jn_17:", Object.keys(J).length, "저널,", n, "페이지");
