import fs from "fs";
const J = { "11. Dead Eyes Cave": {} };
const P = J["11. Dead Eyes Cave"];
const RE = `<p><strong>무작위 사건</strong>: 플레이어 캐릭터들이 이곳에서 온전히 1스트레치를 보낼 때마다 @UUID[.TYgE6fsCbOSQGa2d#random-event]{무작위 사건} 표에 [[/roll D8]]을 굴리세요.</p>`;
const L = { entrance: `@UUID[.jjoGXZUZdGLkWzMk]{동굴 입구}`, snake: `@UUID[.7M4WZ9XePl6N0m6c]{뱀 구덩이}`,
  cult: `@UUID[.k4g8TuSt4ARzInO3]{광신도 야영지}`, gun: `@UUID[.spWVxiJFNUpZH6Cx]{군힐의 야영지}`,
  lair: `@UUID[.vclibIOrVpcQjy66]{바실리스크 소굴}`, out: `@UUID[.NT0LKipLiZcx6l8Y]{동굴 밖}` };

P["Dead Eyes Cave"] = `<p>쿠머 산맥 동쪽의 외딴 절벽에 죽은 눈 동굴이 있습니다. 모두가 피하는 곳이며, 아무것도 자라지 않고, 눈이 있는 생물이라면 무엇도 돌아오지 못하는 곳입니다. 바실리스크가 그곳을 제 소굴로 삼았기 때문입니다. 이 바실리스크는 최근 농장 하나를 덮쳤으며, 아우트스커트에도 심각한 위협이 될 수 있습니다. </p>`;

P["The Situation"] = `<img src="modules/dragonbane-coreset/assets/artwork/adventure/dead-eyes-cave-en.webp" /><p>바실리스크가 아우트스커트 남동쪽 힐디의 농장을 덮쳐, 힐디 본인과 조카 군힐을 뺀 거의 모두를 죽였습니다. 플레이어 캐릭터들은 아우트스커트에서 이 이야기를 들을 수 있습니다(@UUID[JournalEntry.EobTKNtJU1ScMlAa]{소문} 참조). 그 뒤 바실리스크는 오쿨루스 산의 제 소굴로 물러났습니다.</p><p>이 산은 눈을 닮아 그런 이름이 붙었습니다. 바실리스크의 숨결 탓에 그 주변에는 거의 아무것도 자라지 않습니다. 바실리스크는 동굴 바닥에서 쉬지만, 여러 좁은 수직굴과 틈으로 기어 나올 수 있습니다. 힐디의 조카 군힐은 그 짐승을 죽이겠다며 동굴로 향했습니다.</p><p>아즈라헬 코스를 섬기는 광신도들도 용 조각상의 조각을 찾아(<em>용 황제의 비밀</em>을 플레이하지 않는다면 다른 보물을 찾아) 이 동굴에 와 있습니다. 조각상 조각을 이곳에 두기로 했다면 ${L.lair}에서 찾을 수 있습니다.</p><img src="modules/dragonbane-coreset/assets/actors/adventure/hildi.webp" /><blockquote class="info"><h3>힐디와의 만남</h3><p>오쿨루스 산으로 가는 길, 동굴에서 걸어서 한 시간쯤 되는 곳에서 플레이어 캐릭터들은 힐디의 농장을 지납니다. 힐디는 그 짐승이 덮쳤을 때 농장에서 유일하게 살아남은 사람이며, 근처 밭에는 갓 만든 무덤이 여럿 보입니다. 힐디는 눈이 멀었지만 자기가 듣고 맡은 것을 이야기해 줍니다. 끔찍한 악취가 공기를 채우는 가운데 사람과 짐승이 비명을 질렀습니다. 그는 달아나려 했지만 그 짐승에게 가로막혀 죽는 줄 알았는데, 짐승은 그와 닭장은 건드리지 않고 두었습니다. 짐승이 산 쪽으로 스르륵 사라지는 소리를 들었고, 산꼭대기 동굴에서 온 것 같다고 합니다. 힐디는 또 습격 당시 사냥을 나가 있던 조카 군힐이 그 짐승을 죽이러 동굴로 갔다고 말합니다. 힐디는 플레이어 캐릭터들에게 군힐을 찾아 달라고 애원합니다.</p></blockquote><p></p><blockquote class="info"><h3>동굴을 떠난다면?</h3><p>플레이어 캐릭터들이 긴 휴식을 취하러 동굴을 떠난다면, 시프트마다 @UUID[RollTable.BU27Xp8XL0b1g4Yh]{모험 장소를 떠나며}에 D6을 굴리세요.</p></blockquote><p></p><h3>무작위 사건</h3><p>플레이어 캐릭터들이 특정 방에서 무언가를 찾거나 스트레치 휴식을 취하며 온전히 1스트레치를 보낼 때마다 아래 표를 굴리거나 알맞은 사건을 고를 수 있습니다. 무작위 사건이 일어날 수 있는 곳은 방 설명에 표시되어 있습니다.</p><p>@DisplayTable[RollTable.T7M3wrzl6Nqzvy8V]{무작위 사건}</p>`;

P["Outside the Cave"] = `<blockquote class="info"><p><em>짙은 안개가 오쿨루스 산 꼭대기를 뒤덮고 있다. 이 산에 이름을 준 바위 형상의 한복판, 눈동자가 있어야 할 자리에 동굴 입구가 있다. 안은 칠흑같이 어둡고 입구에서는 퀴퀴한 냄새가 풍겨 나온다.</em></p></blockquote><ul><li><p><strong>사체</strong>: 바닥에는 힐디의 농장에서 끌고 온 먹잇감의 피투성이 잔해가 널려 있습니다. 큰 짐승의 것으로 보입니다. 야수 지식 굴림에 성공한 플레이어 캐릭터는 그것이 양과 말의 사체임을 알아봅니다.</p></li><li><p><strong>북쪽</strong>: ${L.entrance}로 가는 길.</p></li></ul>`;

P["Cave Entrance"] = `<blockquote class="info"><p><em>동굴 안은 어둡고 서늘하다. 바깥에서 스며든 안개가 바닥을 덮고 퀴퀴한 냄새는 한층 짙다. 벽은 거칠고 이끼 낀 돌로 이루어져 있다.</em></p></blockquote><ul><li><p><strong>죽은 광신도</strong>: 동굴 입구 안쪽에 검은 옷을 입은 사트모그 광신도가 죽어 있습니다. 눈알이 뽑혔고 몸은 완전히 굳어 있습니다. 시신을 살피는 플레이어 캐릭터는 팔뚝의 사트모그 표식과 목에 난 커다란 물린 자국 둘을 찾아냅니다.</p></li><li style="color:red"><p style="color:black"><em><strong style="color:red">바닥의 자국:</strong> 동굴을 조사하다 숨은 것 찾기에 성공하거나 일부러 자취를 찾는 플레이어 캐릭터는, 커다란 무언가가 여기서 북쪽(${L.snake} 방향)으로 끌려간 자국을 발견합니다.</em></p></li>${RE.replace("<p><strong>", "<li><p><strong>").replace("</p>", "</p></li>")}<li><p><strong>북쪽</strong>: 축축하고 어두운 굴길이 ${L.snake}로 이어집니다.</p></li><li><p><strong>남쪽</strong>: ${L.out}으로 나가는 통로.</p></li><li><p><strong>서쪽</strong>: ${L.cult}로 가는 굴길. 그쪽에서 모닥불의 일렁이는 빛이 보입니다.</p></li></ul><p></p><p></p>`;

P["Snake Pit"] = `<blockquote class="info"><p><em>이 동굴에서는 퀴퀴한 냄새가 코를 찌르는 악취로 바뀐다. 바닥은 구덩이 쪽으로 비스듬히 기울어 있고, 그 바닥이 스멀스멀 움직이는 듯하다. 이제야 바닥 전체가 뱀으로 뒤덮여 있음을 알아챈다. 북쪽으로 가는 유일한 길은 암벽을 따라 난 좁은 선반뿐이다.</em></p></blockquote><ul><li><p><strong>뱀</strong>: 뱀 구덩이를 타고 지나가려면 곡예를 굴려야 합니다. 실패하면 그 플레이어 캐릭터는 구덩이에 빠지며 의지를 굴려 공포에 저항해야 합니다. 그 대상은 즉시 뱀에 물려 D6의 관통 피해를 받고, 그 뒤 차례마다 D6의 피해를 더 받습니다. 갑옷은 효과가 없습니다. 구덩이에서 기어 나오려면 곡예를 다시 굴려야 합니다.</p></li><li style="color:red"><p style="color:black"><em><strong style="color:red">독사:</strong> 뱀 구덩이 북쪽 암벽의 갈라진 틈에 둥지가 있고, 그곳의 @UUID[Actor.3iyueYo4aITZ2sGv]{독사}가 잠에서 깨어 지나가는 플레이어 캐릭터를 덮칩니다.</em></p></li>${RE.replace("<p><strong>", "<li><p><strong>").replace("</p>", "</p></li>")}<li><p><strong>북쪽</strong>: 뱀 구덩이 건너편의 어두운 굴길이 ${L.gun}로 이어집니다.</p></li><li><p><strong>서쪽</strong>: ${L.cult}로 가는 굴길. 그쪽에서 모닥불의 일렁이는 빛이 보입니다.</p></li><li><p><strong>남쪽</strong>: ${L.entrance}로 가는 축축한 굴길.</p></li></ul><p>@DisplayNpc[Actor.3iyueYo4aITZ2sGv named]{독사}</p>`;

P["Cultist Camp"] = `<blockquote class="info"><p><em>이 동굴 한복판에는 모닥불이 있고, 그 연기가 천장의 갈라진 틈으로 빠져나간다. 불빛이 바닥 곳곳에 흩어진 해골과 뼈, 그리고 불가에 둘러앉은 검은 옷차림의 무리를 비춘다. 모두 눈을 가리고 있다. 그들 옆 바닥에는 닭으로 보이는 것이 든 우리가 놓여 있다.</em></p></blockquote><ul><li><p><strong>광신도</strong>는 플레이어 캐릭터와 같은 수입니다. 눈을 가리고 있으므로 플레이어 캐릭터들은 그들을 지나칠 때 은신에 이점을 얻습니다. 들키면 광신도들이 즉시 덤빕니다.</p></li><li><p><strong>닭</strong>: 바실리스크가 이 새를 두려워하기 때문에 광신도들은 닭 두 마리를 우리에 넣어 가져왔습니다.</p></li><li style="color:red"><p style="color:black"><em><strong style="color:red">검:</strong> 뼈 사이를 뒤지는 사람은 숨은 것 찾기 굴림으로 명품 브로드소드를 찾아낼 수 있습니다.</em></p></li>${RE.replace("<p><strong>", "<li><p><strong>").replace("</p>", "</p></li>")}<li><p><strong>동쪽</strong>: ${L.snake}로 가는 통로.</p></li><li><p><strong>남쪽</strong>: ${L.entrance}로 가는 축축한 굴길.</p></li></ul><img src="modules/dragonbane-coreset/assets/actors/adventure/blind-cultists.webp" /><p>@DisplayNpc[Actor.r6GX5UtWL9ZS0Tu0 named]{데몬 광신도}</p>`;

P["Gunhill's Camp"] = `<blockquote class="info"><p><em>커다란 바위가 여럿 놓인 동굴 방. 바닥은 굴러다니는 돌로 덮여 있고 북쪽 벽은 무너져 내린 바위 더미로 막혀 있다. 동쪽 벽 곁에는 담요와 배낭처럼 보이는 것이 놓여 있다.</em></p></blockquote><ul><li style="color:red"><p style="color:black"><em><strong style="color:red">곰덫:</strong> 입구에 곰덫이 놓여 있습니다. 맨 앞에 선 플레이어 캐릭터가 덫을 건드리며, 회피 굴림에 성공하지 못하면 [[/damage D8 slashing]]을 받습니다. 아주 조심스럽게 방에 들어서며 숨은 것 찾기에 성공하면 제때 덫을 알아챌 수 있습니다.</em></p></li><li style="color:red"><p style="color:black"><em><strong style="color:red">군힐:</strong> @UUID[Actor.QDZgCnasQblk3AlS]{힐디의 조카}가 여기 야영지를 차렸고, 플레이어 캐릭터들이 다가오자 바위 뒤에 숨습니다. 누군가 곰덫을 건드리는 순간 검을 뽑고 눈을 가린 채 뛰쳐나옵니다. 군힐은 의심이 많아, 광신도들의 소리를 들은 터라 플레이어 캐릭터들도 그 무리라고 여기지만 설득 굴림으로 진정시킬 수 있습니다.</em></p></li>${RE.replace("<p><strong>", "<li><p><strong>").replace("</p>", "</p></li>")}<li><p><strong>북쪽</strong>: 무너진 바위 더미 뒤에 ${L.lair}이 있습니다. 바위를 치우는 데 1스트레치가 걸리고 힘 굴림에 성공해야 하지만(여러 번 시도할 수 있습니다) 건너편의 바실리스크가 알아챕니다. 바위 사이에 숨은 통로가 있어 곡예 굴림으로 지날 수 있으며, 군힐이 그곳을 압니다. 숨은 통로는 숨은 것 찾기 굴림으로도 찾아낼 수 있습니다.</p></li><li><p><strong>남쪽</strong>: ${L.snake}로 가는 어두운 굴길.</p></li></ul><img src="modules/dragonbane-coreset/assets/actors/adventure/gunhill.webp" /><p>@DisplayNpc[Actor.QDZgCnasQblk3AlS named]{군힐}</p>`;

P["The Basilisk's Lair"] = `<blockquote class="info"><p><em>어둡고 널따란 동굴, 코를 태울 만큼 지독한 악취로 가득하다. 바닥은 뼈 잔해와 썩어 가는 뽑힌 눈알로 뒤덮여 있다. 방 한복판에는 끔찍한 생물이 앉아 있다. 뱀과, 터무니없이 큰 수탉을 뒤섞어 놓은 듯한 모습이다.</em></p></blockquote><ul><li><p><strong>바실리스크</strong>: 이곳이 @UUID[Actor.DLJY31vnnijPlOMp]{그 짐승}의 둥지이며, 플레이어 캐릭터를 알아채는 즉시 덤빕니다. 바위를 뚫고 들어오면 자동으로 알아채지만, 숨은 통로로 오는 캐릭터들은 은신을 굴려 들키지 않을 수 있습니다.</p></li><li><p><strong>보물</strong>: 바실리스크 뒤편 바닥의 뼈 사이에 [[/treasure 3]]에 해당하는 값진 것들이 흩어져 있습니다. 이 어드벤처에 용 조각상 조각을 두기로 했다면 그것도 여기 있습니다.</p></li><li><p><strong>남쪽</strong>: ${L.gun}로 통하는 입구.</p></li></ul><p></p><blockquote class="info"><h3>눈 가리기</h3><p>플레이어 캐릭터들이 (군힐과 광신도들처럼) 눈을 가린다면 바실리스크의 <strong>석화의 응시!</strong> 공격에 면역이 되지만, 동시에 칠흑 같은 @UUID[JournalEntry.SbbSMsuvWeo3HaID.JournalEntryPage.6WPxPxUjh4W80RNy#darkness]{어둠} 속에 있는 것처럼 행동하게 됩니다.</p></blockquote><p>@DisplayMonsterDescriptionCard[Actor.DLJY31vnnijPlOMp named]{바실리스크}</p>`;

fs.writeFileSync("jn_27.json", JSON.stringify(J, null, 1));
let n = 0; for (const p of Object.values(J)) n += Object.keys(p).length;
console.log("jn_27:", Object.keys(J).length, "저널,", n, "페이지");
